export const QUICK_SEARCHES = ["Amoxicillin", "Paracetamol", "Metformin", "Ibuprofen", "Omeprazole"];

export const SEV_COLOR = { high: "#E24B4A", med: "#EF9F27", low: "#1D9E75" };

export const styles = {
  app: { maxWidth: 680, margin: "0 auto", fontFamily: "'DM Sans', sans-serif", paddingBottom: 60 },
  hero: { padding: "40px 24px 28px", background: "linear-gradient(180deg,#E1F5EE 0%,#FAFAF8 100%)", borderBottom: "1px solid #E5E3DC" },
  logoPill: { background: "#1D9E75", color: "#fff", fontSize: 13, fontWeight: 600, padding: "4px 14px", borderRadius: 99, letterSpacing: ".5px", display: "inline-block", marginBottom: 8 },
  tagline: { fontSize: 11, color: "#085041", fontWeight: 500, letterSpacing: ".5px", textTransform: "uppercase", marginBottom: 16 },
  heroTitle: { fontFamily: "'Instrument Serif', serif", fontSize: 34, lineHeight: 1.15, color: "#1a1916", marginBottom: 8 },
  heroTitleEm: { color: "#1D9E75", fontStyle: "italic" },
  heroSub: { fontSize: 14, color: "#5F5E5A", lineHeight: 1.6, maxWidth: 480, marginBottom: 20 },
  langBar: { display: "flex", gap: 8, flexWrap: "wrap", marginTop: 16 },
  langBtnBase: { padding: "5px 16px", borderRadius: 99, border: "1.5px solid #E5E3DC", background: "#fff", fontSize: 13, fontWeight: 500, cursor: "pointer", color: "#5F5E5A", transition: "all .15s" },
  langBtnActive: { background: "#1D9E75", borderColor: "#1D9E75", color: "#fff" },
  content: { padding: "24px" },
  sectionLabel: { fontSize: 11, fontWeight: 600, letterSpacing: ".8px", textTransform: "uppercase", color: "#888780", marginBottom: 12 },
  uploadZone: { border: "2px dashed #E5E3DC", borderRadius: 12, padding: 32, textAlign: "center", cursor: "pointer", background: "#fff", marginBottom: 16, transition: "all .2s" },
  uploadIcon: { width: 48, height: 48, background: "#E1F5EE", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 12px" },
  uploadTitle: { fontSize: 15, fontWeight: 500, color: "#1a1916", marginBottom: 4 },
  uploadSub: { fontSize: 13, color: "#888780" },
  divider: { display: "flex", alignItems: "center", gap: 12, color: "#888780", fontSize: 13, margin: "16px 0" },
  searchRow: { display: "flex", gap: 8 },
  searchInput: { flex: 1, padding: "11px 16px", border: "1.5px solid #E5E3DC", borderRadius: 8, fontSize: 15, outline: "none", background: "#fff", color: "#1a1916", fontFamily: "inherit" },
  searchBtn: { padding: "11px 20px", background: "#1D9E75", color: "#fff", border: "none", borderRadius: 8, fontWeight: 600, fontSize: 14, cursor: "pointer", whiteSpace: "nowrap" },
  quickSearches: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 12 },
  quickPill: { padding: "4px 14px", borderRadius: 99, background: "#F1EFE8", border: "none", fontSize: 12, color: "#5F5E5A", cursor: "pointer", fontFamily: "inherit" },
  spinner: { width: 36, height: 36, border: "3px solid #E1F5EE", borderTopColor: "#1D9E75", borderRadius: "50%", animation: "spin .8s linear infinite", margin: "0 auto 16px" },
  loadingCard: { background: "#fff", border: "1px solid #E5E3DC", borderRadius: 12, padding: 32, textAlign: "center", marginTop: 24 },
  drugCard: { background: "#fff", border: "1px solid #E5E3DC", borderRadius: 12, overflow: "hidden", marginTop: 24 },
  drugHeader: { padding: "20px 24px", background: "#E1F5EE", borderBottom: "1px solid #9FE1CB" },
  drugName: { fontFamily: "'Instrument Serif', serif", fontSize: 28, color: "#085041" },
  drugGeneric: { fontSize: 13, color: "#085041", opacity: .7, marginTop: 2 },
  badgesRow: { display: "flex", gap: 8, flexWrap: "wrap", marginTop: 12 },
  badgeRx: { padding: "3px 10px", borderRadius: 99, fontSize: 11, fontWeight: 600, background: "#A32D2D", color: "#FCEBEB" },
  badgeOtc: { padding: "3px 10px", borderRadius: 99, fontSize: 11, fontWeight: 600, background: "#0F6E56", color: "#E1F5EE" },
  badgeCaution: { padding: "3px 10px", borderRadius: 99, fontSize: 11, fontWeight: 600, background: "#BA7517", color: "#FAEEDA" },
  tabs: { display: "flex", borderBottom: "1px solid #E5E3DC", background: "#fff", padding: "0 24px" },
  tabBase: { padding: "12px 0", marginRight: 20, fontSize: 13, fontWeight: 500, color: "#888780", cursor: "pointer", borderBottom: "2px solid transparent", background: "none", border: "none", fontFamily: "inherit" },
  tabActive: { color: "#1D9E75", borderBottom: "2px solid #1D9E75" },
  drugSection: { padding: "18px 24px", borderBottom: "1px solid #E5E3DC" },
  drugSectionLast: { padding: "18px 24px" },
  sectionTitle: { display: "flex", alignItems: "center", gap: 8, fontSize: 12, fontWeight: 600, letterSpacing: ".6px", textTransform: "uppercase", color: "#888780", marginBottom: 12 },
  tagList: { display: "flex", flexWrap: "wrap", gap: 6 },
  tagAmber: { padding: "5px 12px", borderRadius: 6, fontSize: 13, background: "#FAEEDA", color: "#633806" },
  warningBox: { background: "#FCEBEB", border: "1px solid #F7C1C1", borderRadius: 8, padding: "14px 16px" },
  warningTitle: { fontSize: 13, fontWeight: 600, color: "#A32D2D", marginBottom: 6 },
  infoItem: { background: "#FAFAF8", borderRadius: 8, padding: "10px 12px", marginBottom: 10 },
  infoLabel: { fontSize: 11, color: "#888780", marginBottom: 3, fontWeight: 500 },
  infoValue: { fontSize: 13, color: "#1a1916" },
  disclaimer: { background: "#FAEEDA", border: "1px solid #FAC775", borderRadius: 8, padding: "14px 16px", marginTop: 0 },
  disclaimerTitle: { fontSize: 13, fontWeight: 600, color: "#633806", marginBottom: 4 },
  disclaimerText: { fontSize: 12, color: "#633806", lineHeight: 1.6, opacity: .85 },
  interactionItem: { display: "flex", alignItems: "flex-start", gap: 10, padding: "8px 0", borderBottom: "1px solid #E5E3DC" },
  interactionDrug: { fontSize: 13, fontWeight: 500, color: "#1a1916" },
  interactionDesc: { fontSize: 12, color: "#5F5E5A", marginTop: 2 },
  sevDot: { width: 8, height: 8, borderRadius: "50%", flexShrink: 0, marginTop: 4 },
  previewImg: { width: "100%", maxHeight: 180, objectFit: "contain", borderRadius: 8, marginBottom: 8, border: "1px solid #E5E3DC" },
  previewBar: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 14px", background: "#E1F5EE", borderRadius: 8, marginBottom: 16 },
  emptyState: { padding: "40px 24px", textAlign: "center", color: "#888780" },
};
